/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WithdrawRouteImport } from './routes/withdraw'
import { Route as RecommendationRouteImport } from './routes/recommendation'
import { Route as PolicyRouteImport } from './routes/policy'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ActivityRouteImport } from './routes/activity'
import { Route as IndexRouteImport } from './routes/index'

const WithdrawRoute = WithdrawRouteImport.update({
  id: '/withdraw',
  path: '/withdraw',
  getParentRoute: () => rootRouteImport,
} as any)
const RecommendationRoute = RecommendationRouteImport.update({
  id: '/recommendation',
  path: '/recommendation',
  getParentRoute: () => rootRouteImport,
} as any)
const PolicyRoute = PolicyRouteImport.update({
  id: '/policy',
  path: '/policy',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivityRoute = ActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/dashboard': typeof DashboardRoute
  '/policy': typeof PolicyRoute
  '/recommendation': typeof RecommendationRoute
  '/withdraw': typeof WithdrawRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/dashboard': typeof DashboardRoute
  '/policy': typeof PolicyRoute
  '/recommendation': typeof RecommendationRoute
  '/withdraw': typeof WithdrawRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/dashboard': typeof DashboardRoute
  '/policy': typeof PolicyRoute
  '/recommendation': typeof RecommendationRoute
  '/withdraw': typeof WithdrawRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activity'
    | '/dashboard'
    | '/policy'
    | '/recommendation'
    | '/withdraw'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activity'
    | '/dashboard'
    | '/policy'
    | '/recommendation'
    | '/withdraw'
  id:
    | '__root__'
    | '/'
    | '/activity'
    | '/dashboard'
    | '/policy'
    | '/recommendation'
    | '/withdraw'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActivityRoute: typeof ActivityRoute
  DashboardRoute: typeof DashboardRoute
  PolicyRoute: typeof PolicyRoute
  RecommendationRoute: typeof RecommendationRoute
  WithdrawRoute: typeof WithdrawRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/withdraw': {
      id: '/withdraw'
      path: '/withdraw'
      fullPath: '/withdraw'
      preLoaderRoute: typeof WithdrawRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recommendation': {
      id: '/recommendation'
      path: '/recommendation'
      fullPath: '/recommendation'
      preLoaderRoute: typeof RecommendationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/policy': {
      id: '/policy'
      path: '/policy'
      fullPath: '/policy'
      preLoaderRoute: typeof PolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activity': {
      id: '/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof ActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActivityRoute: ActivityRoute,
  DashboardRoute: DashboardRoute,
  PolicyRoute: PolicyRoute,
  RecommendationRoute: RecommendationRoute,
  WithdrawRoute: WithdrawRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
